### ISSUE TITLE
Use animation instead of transition

### ISSUE THREAD

**Issue by D6C92FE5** [simonmysun/simonmysun.github.io.2015#2]
据说使用 [CSS 动画](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_animations)（而不是 CSS 过度）可以让背景图一直滚动，无论鼠标是否在上面

**Comment by simonmysun** [comment]
竟然用了 js... 不幸福

**Comment by D6C92FE5** [comment]
那个教程里说了可以用 JS 和 CSS 动画交互，不代表要用 CSS 动画就一定要用 JS 吧

**Comment by simonmysun** [comment]
嗯，能行。

不过我想的问题是，CSS animations 得有个起点终点呀，我让整个背景都动起来，它肯定有个尽头。。因为网页不能循环。我当时想解决这个解决不了。。

**Comment by D6C92FE5** [comment]
CSS 动画貌似支持循环，但能不能适用于这个场景我不是很清楚

**Comment by simonmysun** [comment]
倒是可以过去再回来.. 反正目前的实现思路是不大可能循环了.. 因为网页不能头尾相接...

**Comment by simonmysun** [comment]
倒是可以过去再回来.. 反正目前的实现思路是不大可能循环了.. 因为网页不能头尾相接...

**Comment by simonmysun** [comment]
倒是可以过去再回来.. 反正目前的实现思路是不大可能循环了.. 因为网页不能头尾相接...

**Comment by simonmysun** [comment]
倒是可以过去再回来.. 反正目前的实现思路是不大可能循环了.. 因为网页不能头尾相接...

**Comment by simonmysun** [comment]
倒是可以过去再回来.. 反正目前的实现思路是不大可能循环了.. 因为网页不能头尾相接...

**Comment by simonmysun** [comment]
倒是可以过去再回来.. 反正目前的实现思路是不大可能循环了.. 因为网页不能头尾相接...

**Comment by D6C92FE5** [comment]
『因为很重要所以说了6遍』

**Comment by simonmysun** [comment]
OTZ
